apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderitem-webapi-deployment
  labels:
    app: orderitem-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderitem-webapi
  template:
    metadata:
      labels:
        app: orderitem-webapi
    spec:
      containers:
      - name: orderitem-webapi
        image: orderitem.azurecr.io/orderitem-webapirepo:latest1
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentials2
---
apiVersion: v1
kind: Service
metadata:
  name: orderitem-webapisvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: orderitem-webapi